name: CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check update for wonderful toolchain `target-gba-syslibs`
        id: wonderful-latest-commit
        uses: nmbgeek/github-action-get-latest-commit@main
        with:
          repository: WonderfulToolchain/target-gba-syslibs

      - name: Cache wonderful toolchain
        id: cache-wonderful
        uses: actions/cache@v3
        env:
          cache-name: wonderful-toolchain
        with:
          path: /opt/wonderful
          key: ${{runner.os}}-wonderful-${{steps.wonderful-latest-commit.outputs.hash}}

      - name: Install wonderful toolchain
        if: ${{steps.cache-wonderful.outputs.cache-hit != 'true'}}
        run: |
          mkdir /opt/wonderful
          cd /opt/wonderful
          wget -qO- https://wonderful.asie.pl/bootstrap/wf-bootstrap-x86_64.tar.gz | tar xvz
          export PATH=/opt/wonderful/bin:$PATH
          export WONDERFUL_TOOLCHAIN=/opt/wonderful
          wf-pacman -Syu wf-tools --noconfirm
          wf-pacman -Syu wf-tools --noconfirm
          wf-config repo enable blocksds
          wf-pacman -Syu --noconfirm
          wf-pacman -S target-gba --noconfirm
          wf-pacman -S blocksds-toolchain --noconfirm

      - name: Clone Butano
        uses: actions/checkout@v4
        with:
          repository: GValiente/butano
          path: butano

      - name: Build
        run: |
          export PATH=/opt/wonderful/bin:$PATH
          export WONDERFUL_TOOLCHAIN=/opt/wonderful
          make -j$(nproc)

      - name: Pack
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p licenses/butano/
          cp -r butano/licenses/* licenses/butano/
          rm -f licenses/butano/devkitarm*
          zip -r butano-template-${GITHUB_REF_NAME}.zip *.gba licenses

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: butano-template-*.zip
