name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: devkitpro-buildscripts-latest-release
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: devkitPro/buildscripts

      - name: Cache devkitARM
        id: cache-devkitarm
        uses: actions/cache@v3
        env:
          cache-name: cache-devkitarm-packages
        with:
          path: /opt/devkitpro/!(pacman)/**
          key: ${{runner.os}}-devkitarm-${{steps.devkitpro-buildscripts-latest-release.outputs.id}}
      
      - name: Install devkitARM
        if: ${{steps.cache-devkitarm.outputs.cache-hit != 'true'}}
        run: |
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x ./install-devkitpro-pacman
          sudo yes | sudo ./install-devkitpro-pacman
          sudo dkp-pacman -S gba-dev --noconfirm

      - name: Clone Butano
        uses: actions/checkout@v4
        with:
          repository: GValiente/butano
          path: butano

      - name: Build
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=${DEVKITPRO}/devkitARM
          export DEVKITPPC=${DEVKITPRO}/devkitPPC
          export PATH=${DEVKITPRO}/tools/bin:$PATH
          make -j2
